server:
  port: 8080

#spring.jpa:
#  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#  properties.hibernate.jdbc.lob.non_contextual_creation: true
#  database: postgresql
#  hibernate.ddl-auto: update
#  show-sql: true
#
#spring.datasource:
#  url: jdbc:postgresql://localhost:5432/epay_db
#  username: epay_user
#  password: 12345


spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  database: h2
  hibernate.ddl-auto: create-drop
  show-sql: true

spring.datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  driver-class-name: org.h2.Driver
  username: sa
  password: sa

