server:
  port: 8080

spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  database: h2
  hibernate.ddl-auto: create-drop
  show-sql: true

spring.datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  driver-class-name: org.h2.Driver
  username: sa
  password: sa

